version: "3.7"
services:
  app:
    build:
      args:
        user: amgm
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sppd
    container_name: sppd-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

    nginx:
    image: nginx:alpine
    container_name: sppd-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./Apps/nginx:/etc/nginx/conf.d/