version: "3.7"
services:
  app:
    build: ./Apps
    image: sppd
    container_name: sppd-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: sppd-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html
      - ./Apps/nginx:/etc/nginx/conf.d/